"use client";
import {useState} from "react";
import {LayoutDashboard,BriefcaseBusiness,Users,UserSearch,Network,WalletCards,KeyRound,Search,Bell,Plus,ArrowUpRight,MoreHorizontal,SlidersHorizontal,Building2,CalendarDays,ChevronRight,TrendingUp,CircleCheck,MapPin,Sparkles,FileText,ShieldCheck,Phone,Mail,ExternalLink,X} from "lucide-react";

type Section="Resumen"|"Necesidades"|"Candidatos"|"Empleados"|"Organigrama"|"Costes"|"Accesos"|"Cazador de Talento";
const modules:any[]=[["Resumen",LayoutDashboard,"Vista general"],["Necesidades",BriefcaseBusiness,"8 abiertas"],["Candidatos",UserSearch,"24 activos"],["Cazador de Talento",Sparkles,"Búsqueda IA"],["Empleados",Users,"47 personas"],["Organigrama",Network,"Estructura"],["Costes",WalletCards,"Control económico"],["Accesos",KeyRound,"3 revisiones"]];
const needs:any[]=[
["Desarrollador/a Full Stack","Tech-On","Producto / IT","Entrevistas","purple","Alta","25 ago",6,94],
["Director/a Comercial B2B","Contact-On","Comercial","En búsqueda","blue","Urgente","18 ago",11,87],
["Especialista SEO","Impact-On","Marketing","Aprobada","amber","Media","10 sep",3,81],
["Técnico/a de Hardware","Vulcan","Producto / IT","Solicitada","gray","Media","15 sep",0,0]];
const people:any[]=[
["Pablo Ferrer","PF","Tech Lead / Product Owner","Tech-On","Producto / IT","4.280 €",["Base44 5","APIs 5","Equipos 4"]],
["Carmen Ruiz","CR","Responsable de Marketing","Impact-On","Marketing","3.460 €",["Marketing 5","Meta Ads 4","SEO 4"]],
["Gabriel Torres","GT","Supervisor de Operaciones","Contact-On","Operaciones","3.150 €",["Equipos 5","CRM 4","Ventas 4"]],
["Nati Beltrán","NB","Diseñadora UX/UI","Tech-On","Producto / IT","3.020 €",["UX/UI 5","Figma 5","Base44 3"]]];
const candidates:any[]=[["Álvaro Martín","AM","Desarrollador Full Stack","Alicante","LinkedIn",94,["Base44 5","n8n 4","APIs 5"]],["Marta Soler","MS","Especialista SEO","Valencia","InfoJobs",91,["SEO 5","Analytics 4","WordPress 4"]],["Javier Ortega","JO","Director Comercial B2B","Benidorm","Manual",87,["Ventas B2B 5","Equipos 4","CRM 4"]]];

export default function Home(){
 const [section,setSection]=useState<Section>("Resumen"),[navOpen,setNavOpen]=useState(true),[modal,setModal]=useState(false),[person,setPerson]=useState<any>(null),[toast,setToast]=useState("");
 const say=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};
 return <div className="appShell"><aside className="sidebar"><div className="brand"><div className="brandMark">L</div><div><strong>LEYVA</strong><span>GROUP</span></div></div><div className="workspace"><div className="workspaceIcon"><Building2 size={17}/></div><div><span>ESPACIO DE TRABAJO</span><strong>Leyva Group</strong></div><ChevronRight size={16}/></div><nav><p>GESTIÓN</p><button className="talentToggle active" onClick={()=>setNavOpen(!navOpen)} aria-expanded={navOpen}><LayoutDashboard size={18}/><span>Panel Talento</span><b>8</b><ChevronRight className={navOpen?"open":""} size={15}/></button>{navOpen&&<div className="talentSubmenu">{modules.map(m=>{const I=m[1];return <button key={m[0]} className={section===m[0]?"selected":""} onClick={()=>setSection(m[0])}><I size={16}/><span>{m[0]}</span></button>})}</div>}</nav><div className="sideBottom"><div className="user"><div className="avatar dark">DL</div><div><strong>David Leyva</strong><span>Administrador</span></div><MoreHorizontal size={18}/></div></div></aside>
 <main><header><div className="search"><Search size={18}/><input placeholder="Buscar personas, skills, puestos..."/><kbd>⌘ K</kbd></div><button className="iconBtn"><Bell size={19}/><i/></button><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/> Nueva necesidad</button></header><div className="content">
 {section==="Resumen"&&<Dashboard go={setSection} open={setPerson}/>}
 {section==="Necesidades"&&<Needs onNew={()=>setModal(true)}/>}
 {section==="Candidatos"&&<Candidates say={say}/>}
 {section==="Empleados"&&<Employees open={setPerson}/>}
 {section==="Organigrama"&&<Org open={setPerson}/>}
 {section==="Costes"&&<Costs/>}
 {section==="Accesos"&&<Access say={say}/>}
 {section==="Cazador de Talento"&&<TalentHunter say={say}/>}
 </div></main>{modal&&<NewNeed close={()=>setModal(false)} save={()=>{setModal(false);say("Necesidad creada correctamente")}}/>}{person&&<Drawer p={person} close={()=>setPerson(null)}/>} {toast&&<div className="toast"><CircleCheck size={18}/>{toast}</div>}</div>
}
function Title({eye,title,text,action}:any){return <div className="pageTitle"><div><span>{eye}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Dashboard({go,open}:any){return <><Title eye="MIÉRCOLES, 12 DE AGOSTO" title="Buenos días, David" text="Esta es la situación actual del talento en Leyva Group." action={<button className="outline"><CalendarDays size={17}/> Últimos 30 días <ChevronRight size={15}/></button>}/><section className="kpiGrid"><Kpi l="PERSONAS EN EL GRUPO" v="47" t="+3 este trimestre" icon={<Users/>} tone="blue"/><Kpi l="NECESIDADES ABIERTAS" v="8" t="3 de prioridad alta" icon={<BriefcaseBusiness/>} tone="purple"/><Kpi l="CANDIDATOS ACTIVOS" v="24" t="7 nuevos esta semana" icon={<UserSearch/>} tone="orange"/><Kpi l="COSTE MENSUAL REAL" v="128.450 €" t="+2,4% vs. julio" icon={<WalletCards/>} tone="green"/></section><section className="twoCol topGap"><div className="card"><Head t="Necesidades prioritarias" s="Procesos que requieren atención" a="Ver todas" click={()=>go("Necesidades")}/><div>{needs.slice(0,3).map(n=><NeedRow key={n[0]} n={n}/>)}</div></div><div className="card costCard"><Head t="Coste de personal" s="Distribución mensual por empresa" a="Detalle" click={()=>go("Costes")}/><div className="costTotal"><div><span>TOTAL MENSUAL</span><strong>128.450 €</strong></div><div className="budget"><span>Presupuesto utilizado</span><b>91%</b></div></div><div className="stacked"><i/><i/><i/><i/><i/></div><div className="legend">{[["Tech-On","39.810 €"],["Contact-On","32.120 €"],["Linmania","24.410 €"],["Impact-On","18.360 €"],["Otras","13.750 €"]].map((x,i)=><span key={x[0]}><i className={"l"+(i+1)}/>{x[0]} <b>{x[1]}</b></span>)}</div></div></section><section className="card topGap"><Head t="Equipo y skills destacadas" s="Personas con capacidades clave para los proyectos actuales" a="Ver empleados" click={()=>go("Empleados")}/><div className="peopleGrid">{people.slice(0,3).map((p,i)=><PersonCard key={p[0]} p={p} i={i} click={()=>open(p)}/>)}</div></section></>}
function Kpi({l,v,t,icon,tone}:any){return <div className="kpi card"><div className={"kpiIcon "+tone}>{icon}</div><span>{l}</span><strong>{v}</strong><p><TrendingUp size={14}/>{t}</p></div>}
function Head({t,s,a,click}:any){return <div className="cardHead"><div><h2>{t}</h2><p>{s}</p></div>{a&&<button onClick={click}>{a}<ArrowUpRight size={15}/></button>}</div>}
function NeedRow({n}:any){return <div className="needRow"><div className={"roleIcon "+n[4]}><BriefcaseBusiness size={18}/></div><div className="grow"><strong>{n[0]}</strong><span>{n[1]} · {n[2]}</span></div><div className={"status "+n[4]}>{n[3]}</div><div className="miniData"><span>Candidatos</span><b>{n[7]}</b></div><MoreHorizontal size={18}/></div>}
function PersonCard({p,i,click}:any){return <button className="personCard" onClick={click}><div className={"avatar big a"+i}>{p[1]}</div><div className="grow"><strong>{p[0]}</strong><span>{p[2]}</span><p>{p[6].slice(0,2).map((s:string)=><em key={s}>{s}</em>)}</p></div><ChevronRight size={18}/></button>}
function Needs({onNew}:any){return <><Title eye="PLANIFICACIÓN DE EQUIPO" title="Solicitudes de personal" text="Controla cada necesidad desde la solicitud hasta su incorporación." action={<button className="primary" onClick={onNew}><Plus size={18}/> Nueva solicitud</button>}/><div className="pipeline">{[["Solicitada",2],["Aprobada",1],["En búsqueda",3],["Entrevistas",2],["Cubierta",5]].map((x,i)=><div key={x[0]} className={i===3?"focus":""}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div><div className="card tableCard"><div className="tableTools"><div className="search small"><Search size={17}/><input placeholder="Buscar puesto..."/></div><button className="outline"><SlidersHorizontal size={16}/> Filtros</button></div><div className="table"><div className="tr th"><span>Puesto / empresa</span><span>Estado</span><span>Prioridad</span><span>Fecha prevista</span><span>Candidatos</span><span>Adecuación</span></div>{needs.map(n=><div className="tr" key={n[0]}><span><strong>{n[0]}</strong><small>{n[1]} · {n[2]}</small></span><span><i className={"status "+n[4]}>{n[3]}</i></span><span><b className={"priority "+n[5]}>{n[5]}</b></span><span>{n[6]}</span><span>{n[7]}</span><span><b>{n[8]?n[8]+"%":"—"}</b></span></div>)}</div></div></>}
function Candidates({say}:any){return <><Title eye="CAPTACIÓN Y MATCHING IA" title="Candidatos" text="Perfiles centralizados y ordenados por adecuación a tus necesidades." action={<button className="primary" onClick={()=>say("Importación de candidatos preparada")}><Plus size={18}/> Añadir candidato</button>}/><div className="aiBanner"><div><Sparkles size={22}/></div><p><strong>Matching inteligente activo</strong><span>La IA ha analizado 24 perfiles y detectado 5 coincidencias superiores al 85%.</span></p><button onClick={()=>say("Mostrando las 5 mejores coincidencias")}>Ver coincidencias</button></div><div className="candidateGrid">{candidates.map((c,i)=><div className="card candidate" key={c[0]}><div className="candidateTop"><div className={"avatar big a"+i}>{c[1]}</div><div className="grow"><h3>{c[0]}</h3><p>{c[2]}</p><span><MapPin size={13}/>{c[3]} · {c[4]}</span></div><div className="fit"><strong>{c[5]}%</strong><span>Adecuación</span></div></div><div className="skillTags">{c[6].map((s:string)=><i key={s}>{s}</i>)}</div><div className="candidateActions"><button className="outline" onClick={()=>say("Perfil de "+c[0]+" abierto")}>Ver perfil</button><button className="primary" onClick={()=>say(c[0]+" pasa a entrevista")}>Entrevistar</button></div></div>)}</div></>}
function Employees({open}:any){return <><Title eye="EQUIPO ACTUAL" title="Empleados" text="Ficha maestra, documentación, skills y situación de cada persona." action={<button className="primary"><Plus size={18}/> Nueva persona</button>}/><div className="toolbar"><div className="search small wide"><Search size={17}/><input placeholder="Buscar por nombre, puesto o skill..."/></div><button className="outline"><Building2 size={16}/> Todas las empresas</button><button className="outline"><SlidersHorizontal size={16}/> Más filtros</button></div><div className="employeeGrid">{people.map((p,i)=><div className="card employee" key={p[0]} onClick={()=>open(p)}><div className="employeeHead"><div className={"avatar big a"+i}>{p[1]}</div><span className="live">Activo</span></div><h3>{p[0]}</h3><p>{p[2]}</p><span>{p[3]} · {p[4]}</span><div className="skillTags">{p[6].map((s:string)=><i key={s}>{s}</i>)}</div><div className="employeeFoot"><span>Coste mensual <b>{p[5]}</b></span><ChevronRight size={17}/></div></div>)}</div></>}
function Org({open}:any){const [view,setView]=useState("Holding completo");return <><Title eye="ESTRUCTURA ORGANIZATIVA" title="Organigrama" text="Visualiza responsables, equipos, puestos y vacantes del grupo." action={<div className="segmented">{["Holding completo","Por empresa","Por departamento"].map(x=><button className={view===x?"active":""} onClick={()=>setView(x)} key={x}>{x}</button>)}</div>}/><div className="card org"><div className="orgNode boss"><div className="avatar dark">DL</div><div><strong>David Leyva</strong><span>Dirección · Leyva Group</span></div></div><div className="orgLine"/><div className="orgBranches">{people.slice(0,3).map((p,i)=><div className="branch" key={p[0]}><div className="orgNode" onClick={()=>open(p)}><div className={"avatar a"+i}>{p[1]}</div><div><strong>{p[0]}</strong><span>{p[4]}</span><small>{[8,6,14][i]} personas</small></div></div><div className="miniTeam"><span>{i===0?"Desarrollo":"Equipo operativo"}</span><span>{i===1?"Diseño y contenidos":"+ vacantes abiertas"}</span></div></div>)}</div></div></>}
function Costs(){return <><Title eye="CONTROL ECONÓMICO" title="Coste de personal" text="Coste real consolidado, presupuesto y evolución por unidad." action={<button className="outline"><CalendarDays size={17}/> Agosto 2026</button>}/><section className="kpiGrid"><Kpi l="COSTE MENSUAL" v="128.450 €" t="2,4% sobre julio" icon={<WalletCards/>} tone="green"/><Kpi l="COSTE ANUAL PROYECTADO" v="1.541.400 €" t="Dentro de presupuesto" icon={<TrendingUp/>} tone="blue"/><Kpi l="COSTE MEDIO / PERSONA" v="2.733 €" t="47 personas activas" icon={<Users/>} tone="purple"/><Kpi l="PRESUPUESTO DISPONIBLE" v="12.680 €" t="9% del mensual" icon={<CircleCheck/>} tone="orange"/></section><div className="twoCol topGap"><div className="card chartCard"><Head t="Evolución mensual" s="Coste total real · últimos 6 meses"/><div className="chart"><div className="ylabels"><span>140k</span><span>120k</span><span>100k</span><span>80k</span></div><div className="bars">{[104,108,112,119,125,128].map((v,i)=><div key={v}><i style={{height:(v-75)*2.2+"px"}}/><b>{v}k</b><span>{["Mar","Abr","May","Jun","Jul","Ago"][i]}</span></div>)}</div></div></div><div className="card breakdown"><Head t="Composición del coste" s="Agosto 2026"/><div className="donut"><div><strong>128k</strong><span>Total</span></div></div><ul>{[["Salario bruto","78.640 €","61%"],["Seguridad Social","31.720 €","25%"],["Variable / comisiones","12.840 €","10%"],["Otros costes","5.250 €","4%"]].map(x=><li key={x[0]}><i/>{x[0]}<b>{x[1]}</b><span>{x[2]}</span></li>)}</ul></div></div></>}
function Access({say}:any){const sys=[["Google Workspace","Google",42,1,"G"],["Task-On","Software",47,0,"T"],["GESIO","Software",12,1,"GE"],["GitHub","Desarrollo",8,0,"GH"],["Cloudflare","Web",4,1,"C"],["Líneas y extensiones","Comunicaciones",26,0,"☎"]];return <><Title eye="SEGURIDAD Y RECURSOS" title="Accesos digitales" text="Controla sistemas, permisos, responsables y bajas pendientes." action={<button className="primary" onClick={()=>say("Nuevo acceso listo para configurar")}><Plus size={18}/> Asignar acceso</button>}/><div className="accessAlert"><ShieldCheck size={22}/><div><strong>3 revisiones pendientes</strong><span>Hay accesos que requieren validación o actualización de responsable.</span></div><button onClick={()=>say("Revisiones pendientes filtradas")}>Revisar ahora</button></div><div className="systemGrid">{sys.map(s=><div className="card system" key={s[0]}><div className="systemIcon">{s[4]}</div><MoreHorizontal size={18}/><h3>{s[0]}</h3><p>{s[1]}</p><div><span><Users size={14}/>{s[2]} usuarios</span>{Number(s[3])>0&&<b>{s[3]} pendiente</b>}</div><button onClick={()=>say("Accesos de "+s[0]+" abiertos")}>Gestionar <ArrowUpRight size={15}/></button></div>)}</div></>}
function TalentHunter({say}:any){return <><Title eye="BÚSQUEDA INTELIGENTE" title="Cazador de Talento" text="Describe el perfil que necesitas y la IA buscará coincidencias entre candidatos y empleados." action={<button className="primary" onClick={()=>say("Búsqueda inteligente iniciada")}><Sparkles size={17}/> Buscar talento</button>}/><div className="hunterHero card"><div className="hunterIcon"><Sparkles size={25}/></div><div className="hunterPrompt"><label>¿Qué perfil estás buscando?</label><div><Search size={18}/><input placeholder="Ej. Necesito una persona con n8n nivel 4, APIs y experiencia gestionando equipos"/><button onClick={()=>say("Analizando skills y perfiles disponibles")}>Analizar</button></div><p>Puedes buscar por skill, nivel, experiencia, ubicación, empresa o disponibilidad.</p></div></div><div className="hunterStats"><div className="card"><span>PERFILES ANALIZADOS</span><strong>71</strong><small>Empleados y candidatos</small></div><div className="card"><span>COINCIDENCIAS ALTAS</span><strong>12</strong><small>Adecuación superior al 80%</small></div><div className="card"><span>BÚSQUEDAS ACTIVAS</span><strong>4</strong><small>Procesos en seguimiento</small></div></div><div className="card hunterResults"><Head t="Coincidencias recomendadas" s="Resultados sugeridos según las necesidades abiertas"/>{candidates.map((c:any,i:number)=><div className="hunterRow" key={c[0]}><div className={"avatar big a"+i}>{c[1]}</div><div className="grow"><strong>{c[0]}</strong><span>{c[2]} · {c[3]}</span><div className="skillTags">{c[6].map((s:string)=><i key={s}>{s}</i>)}</div></div><div className="fit"><strong>{c[5]}%</strong><span>Adecuación</span></div><button className="outline" onClick={()=>say("Perfil de "+c[0]+" abierto")}>Ver perfil</button></div>)}</div></>}
function NewNeed({close,save}:any){return <div className="modalBack" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span>NUEVA SOLICITUD</span><h2>Necesidad de personal</h2><p>Define el perfil que necesita el equipo.</p></div><button onClick={close}><X/></button></div><div className="form"><label className="full">Puesto<input placeholder="Ej. Desarrollador/a Full Stack"/></label><label>Empresa<select><option>Tech-On</option><option>Contact-On</option><option>Impact-On</option></select></label><label>Departamento<select><option>Producto / IT</option><option>Marketing</option><option>Comercial</option></select></label><label className="full">Motivo<textarea placeholder="¿Por qué se necesita esta incorporación?"/></label><label className="full">Skills necesarias<input placeholder="Base44, n8n, APIs, gestión de equipos..."/></label><label>Coste objetivo<input placeholder="2.800 € / mes"/></label><label>Prioridad<select><option>Media</option><option>Alta</option><option>Urgente</option></select></label></div><div className="modalFoot"><button className="outline" onClick={close}>Cancelar</button><button className="primary" onClick={save}><CircleCheck size={17}/> Crear solicitud</button></div></div></div>}
function Drawer({p,close}:any){return <div className="drawerBack" onMouseDown={close}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><div className="profileTop"><div className="avatar profile">{p[1]}</div><span className="live">Activo</span><h2>{p[0]}</h2><p>{p[2]}</p><small>{p[3]} · {p[4]}</small></div><div className="profileStats"><div><span>Alta</span><b>12 feb 2024</b></div><div><span>Coste mensual</span><b>{p[5]}</b></div></div><section><h3>Skills</h3><div className="skillList">{p[6].map((s:string)=>{const level=Number(s.slice(-1));return <div key={s}><span>{s.slice(0,-2)}</span><div>{[1,2,3,4,5].map(n=><i className={n<=level?"on":""} key={n}/>)}</div><b>{level}/5</b></div>})}</div></section><section><h3>Documentación</h3><button className="doc"><FileText/><div><strong>Contrato laboral</strong><span>PDF · Actualizado</span></div><CircleCheck/></button><button className="doc"><FileText/><div><strong>Currículum</strong><span>PDF · 1,2 MB</span></div><ExternalLink/></button></section><section><h3>Accesos principales</h3><div className="contact"><span><Mail/>Workspace</span><b>Activo</b></div><div className="contact"><span><KeyRound/>Task-On</span><b>Editor</b></div><div className="contact"><span><Phone/>Extensión</span><b>204</b></div></section></aside></div>}
